[package]
name = "brio-smart-tech"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = "0.11.8"
strum = { version = "0.27.2", features = ["derive", "strum_macros"] }
tokio = { version = "1.49", features = ["full"] }
uuid = "1.20.0"
