[package]
name = "brio-bluetooth"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = "0.10"
strum = { version = "0.27.2", features = ["derive", "strum_macros"] }
tokio = { version = "1.28", features = ["full"] }
uuid = "1.11.1"
